name: Generate Snake Animation

on:
  schedule:
    # Runs every 24 hours
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - uses: Platane/snk@d8f161048b11545ae02a8db481c7ffeb650c8e10 # v3.3.0
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Push Snake SVG to Output Branch
        uses: crazy-max/ghaction-github-pages@db64fbe0085e1e10de768b31a9c7e2d3055996ec # v4.0.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
